pipeline {
    agent{
        node {label 'labelName'}
        docker{
            image 'maven:3.6.1-jdk-8-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage('build') {
            steps {
                echo 'Compiling worked app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
         stage('test') {
            steps {
                echo 'Running unit test on worker app'
            }
        }
         stage('package') {
            steps {
                echo 'Packing worker app'
            }
        }
    }
    post {
        always{
            echo 'Build pipeline for worker is completed ...'
        }
    }
}
