pipeline {
    agent any
    tools{
        maven 'Maven 3.6.1'
    }
    stages {
        stage('build') {
             when{
                changeset '**/worker/**'
             }
            steps {
                echo 'Compiling worked app'
                dir('worker'){
                    sh 'mvn compile'
                }
            }
        }
         stage('test') {
              when{
                changeset '**/worker/**'
             }
            steps {
                echo 'Running unit test on worker app'
                dir('worker'){
                   sh 'mvn clean test'
                }
               
            }
        }
         stage('package') {
            when{
                branch 'master'
                changeset '**/worker/**'
             }
            steps {
                echo 'Packing worker app'
                dir('worker'){
                   sh 'mvn package -DskipTests'
                   archiveArtifacts artifacts:'**/target/*.jar', fingerprint:true

                }
            }
        }
    }
    post {
        always{
            echo 'Build pipeline for worker is completed ...'
        }
    }
}
